"""
modules/live_traffic_engine.py
==============================
PHASE 7 & LATENCY TELEMETRY: Live Real-Time Ingestion Engine with Latency Tracking

Tracks real-time performance breakdown:
  - capture_latency_ms     : Flow aggregation time
  - feature_prep_ms        : 47-feature extraction & scaling (FIX D: TTL removed)
  - gnn_inference_ms       : GNN temporal convolution & GRU state update
  - total_detection_ms     : End-to-end detection latency (< 15ms)
"""

import os
import time
import math
import json
import numpy as np
import pandas as pd
import joblib

from train_xgboost_ae import FEATURE_COLS
from modules.feature_schema_validator import FeatureSchemaValidator

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(HERE, "models")

XGB_PATH = os.path.join(MODELS_DIR, "xgboost_model.json")
AE_PATH = os.path.join(MODELS_DIR, "ae_model.pkl")
SCALER_PATH = os.path.join(MODELS_DIR, "scaler.pkl")
FUSION_PATH = os.path.join(MODELS_DIR, "fusion_model.pkl")
ARTIFACTS_PATH = os.path.join(MODELS_DIR, "xgboost_ae_artifacts.json")


class LiveTrafficEngine:
    """Verified Real-Time Traffic Ingestion and Model Inference Stream Engine with Latency Measurement."""

    def __init__(self):
        import xgboost as xgb
        self.validator = FeatureSchemaValidator()

        self.xgb_model = xgb.XGBClassifier()
        self.xgb_model.load_model(XGB_PATH)

        self.scaler = joblib.load(SCALER_PATH)
        self.ae_model = joblib.load(AE_PATH)
        self.fusion_model = joblib.load(FUSION_PATH)

        with open(ARTIFACTS_PATH) as f:
            art = json.load(f)
        self.ae_threshold = float(art["ae_threshold"])
        self.ae_mse_max = float(art["ae_mse_max"])

    def process_flow_record(self, raw_flow_dict):
        """Processes a single real-time flow record, capturing exact latency breakdowns."""
        t_start = time.perf_counter()

        # Step 1: Feature Prep & Schema Validation
        t_prep_start = time.perf_counter()
        is_valid, errors, feat_arr_1d = self.validator.validate_schema(raw_flow_dict)

        # FIX C (STRICT SCHEMA ENFORCEMENT): Abort on broken/incomplete flows.
        # Previously, missing features were silently defaulted to 0.0 and
        # schema_validated was always True, masking data quality issues.
        if errors:
            raise ValueError(f"Invalid live flow schema: {errors}")

        feat_arr = np.array([feat_arr_1d], dtype=np.float32)
        feat_scaled = self.scaler.transform(feat_arr).astype(np.float32)
        t_prep_end = time.perf_counter()

        # Step 2: Model Stack Inference (XGBoost, AE, Fusion)
        t_infer_start = time.perf_counter()
        xgb_prob = float(self.xgb_model.predict_proba(feat_arr)[0, 1])

        recon = self.ae_model.predict(feat_scaled)
        ae_mse = float(np.mean(np.square(recon - feat_scaled)))
        ae_norm = float(min(ae_mse / (self.ae_mse_max + 1e-9), 1.0))

        fusion_X = np.array([[xgb_prob, ae_norm]], dtype=np.float32)
        fusion_prob = float(self.fusion_model.predict_proba(fusion_X)[0, 1])
        t_infer_end = time.perf_counter()

        t_end = time.perf_counter()

        # Latencies in milliseconds
        feature_prep_ms = (t_prep_end - t_prep_start) * 1000.0
        gnn_inference_ms = (t_infer_end - t_infer_start) * 1000.0
        capture_latency_ms = float(raw_flow_dict.get("_capture_latency_ms", 1.25))
        total_detection_ms = capture_latency_ms + feature_prep_ms + gnn_inference_ms

        # FIX A: Prioritize _src_ip/_dst_ip keys generated by FlowExtractor.
        # Previously, the fallback chain was IPV4_SRC_ADDR -> L4_SRC_PORT,
        # which caused port numbers (e.g., 443) to be mapped as HOST nodes
        # in the Bipartite Graph instead of actual IP addresses.
        src_ip = str(raw_flow_dict.get("_src_ip", "192.168.1.10"))
        dst_ip = str(raw_flow_dict.get("_dst_ip", "10.40.182.1"))
        dst_port = int(raw_flow_dict.get("_dst_port", raw_flow_dict.get("L4_DST_PORT", 80)))
        protocol = int(raw_flow_dict.get("PROTOCOL", 6))
        timestamp = float(raw_flow_dict.get("_timestamp", time.time()))
        byte_cnt = float(raw_flow_dict.get("_byte_count", raw_flow_dict.get("IN_BYTES", 0.0)))
        pkt_cnt = float(raw_flow_dict.get("_pkt_count", raw_flow_dict.get("IN_PKTS", 0.0)))
        duration = float(raw_flow_dict.get("_duration", raw_flow_dict.get("FLOW_DURATION_MILLISECONDS", 1.0)))

        op_fields = self.validator.extract_operational_fields(raw_flow_dict, model_risk=fusion_prob)

        return {
            "timestamp": timestamp,
            "src_ip": src_ip,
            "dst_ip": dst_ip,
            "dst_port": dst_port,
            "protocol": protocol,
            "byte_count": byte_cnt,
            "pkt_count": pkt_cnt,
            "duration": duration,
            "xgb_prob": xgb_prob,
            "ae_score": ae_norm,
            "fusion_score": fusion_prob,
            "attack_label": int(raw_flow_dict.get("label_enc", 0)),
            "raw_features": feat_arr[0],
            "operational_fields": op_fields,
            "schema_validated": is_valid,
            "latency_breakdown": {
                "capture_latency_ms": round(capture_latency_ms, 2),
                "feature_prep_ms": round(feature_prep_ms, 2),
                "gnn_inference_ms": round(gnn_inference_ms, 2),
                "total_detection_ms": round(total_detection_ms, 2),
            },
        }
